/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        RentalAgency agency = new RentalAgency();

        // Include vehicles
        agency.includeVehicle(new Car("C1", "Nissan Altima", 50.0, true));
        agency.includeVehicle(new Car("C2", "Honda Civic", 45.0, false));
        agency.includeVehicle(new Motocycle("m1", "Ducati", 44));
        agency.includeVehicle(new Truck("t1", "Ram", 94));

        // Display vehicles
        agency.displayVehicles();

        // Rent a vehicle
        Customer customer1 = new Customer("Randy", 55);
        Customer customer2 = new Customer("Rose" , 63);
        Customer customer3 = new Customer("Tee" , 34);

        agency.rentVehicle("C1", customer1, 5);
        agency.rentVehicle("m1", customer2, 2);
        agency.rentVehicle("t1", customer3, 3);



        // Display transactions
        agency.displayTransactions();

        // Return a vehicle
        agency.returnRentedVehicle("T1");

        // Display transactions again
        agency.displayTransactions();
    }
}
